name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  libft-test:
    runs-on: ubuntu-latest                
    defaults:
      run:
        working-directory: .ft_printfTester

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y make gcc valgrind 

      - name: Run tests
        run: TERM=xterm make